name: Branch cleanup execute on comment

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  issues: write

jobs:
  run-cleanup:
    if: |
      github.event.issue.state == 'open' &&
      contains(github.event.comment.body, '@Cursor run script with -s --execute')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - name: Execute cleanup including stale
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          uv run --with=requests python3 scripts/cleanup_closed_pr_branches.py --with-stale --behind 10 --days 7 --execute > out.txt
          echo "Cleanup executed. See log below." > msg.txt
          echo >> msg.txt
          cat out.txt >> msg.txt
      - name: Comment results and close issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const body = fs.readFileSync('msg.txt', 'utf8');
            await github.issues.createComment({ owner: context.repo.owner, repo: context.repo.repo, issue_number: context.issue.number, body });
            await github.issues.update({ owner: context.repo.owner, repo: context.repo.repo, issue_number: context.issue.number, state: 'closed' });

