name: build

on:
  push:

jobs:
  build:
    name: Build and verify CLI
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Add uv to PATH
        run: echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Build (install tool)
        run: bash ./install.sh

      - name: Verify CLI is available
        run: prin --help > /dev/null

